env:
  global:
   - secure: "XXWQ9WPknj3dAN1c2/ummDq5nL3UKMgaVRKtd1Dv7jOcW9W8roAJhrsoNU2URvtPvxvAOTS8pjQPUTkq1a0vhOdmUTBos1g1q2H5Nn4pfBBhIVKnaU2ds+ugiPaGxzyc7u1X9D32GWfcPZOspoppCSEhVtUkxFLNuNQCKWor0ybfT13q/4Q7gGyq3pocelNH1MOXm/VBsC644tec+DXvu1R3dLOOYFjzpksM31Xf8vddodwWdeMcZxJFXDEhQOw86/CdKv4s7Xr1MyKuoqDhCn9pKqNQduPgE4XDWQaawT0rbIF+a81eg3kMt3PpEL4Zr0hUXw1vzg/lDMBIFd53XdBQV7FCkWOKURGcd/tcM28KM+3QYxlEO1VlyF8wZHT/I0dypS6vnDOuTqHcs2b9Yo62iiBzkqYn8fEtm2a4aRg9z18c7Ze/ZZjxJLhA4jYpMAP0643xE6LvnK4qoeqIEWrZsdpF8tDduRXe1nuzFlILifaksqXi1lf51s+oJGJLTETeT+ypdEGFiCG8JMMJ0XC8/MDb7/obBJvrjZ1J4jtRX7TnDAV9/BvODF1ZF7cs2dqEV6dHNwiNn6zwbESRrU1e9x6AuUNWGD/8GgGouRB1XhgqlAX4YcuCiEuaVXj6ZpsWyPITa+RwMP6HueZkqsMP1UF/SSrKt0lg14QUN9A="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "klaussilveira/qengine"
    notification_email: contact@klaussilveira.com
    build_command_prepend: "mkdir build && cd build && cmake .."
    build_command: "make -j2"
    branch_pattern: coverity_scan

language: c
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make lint_check

matrix:
  include:
    - env: PLATFORM=Unix COMPILER=gcc-6
      compiler: gcc
      os: linux
      addons:
        apt:
          packages: ['gcc-6', 'g++-6']
          sources: &sources
            - ubuntu-toolchain-r-test

    - env: PLATFORM=Unix COMPILER=gcc-7
      compiler: gcc
      os: linux
      addons:
        apt:
          packages: ['gcc-7', 'g++-7']
          sources: &sources
            - ubuntu-toolchain-r-test

    - env: PLATFORM=Unix COMPILER=clang-3.6
      compiler: clang
      os: linux
      addons:
        apt:
          packages: ['clang-3.6', 'clang++-3.6']
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

    - env: PLATFORM=Unix COMPILER=clang-5.0
      compiler: clang
      os: linux
      addons:
        apt:
          packages: ['clang-5.0', 'clang++-5.0']

    - env: PLATFORM=Unix COMPILER=clang-6.0
      compiler: clang
      os: linux
      addons:
        apt:
          packages: ['clang-6.0', 'clang++-6.0']
