name: Build
on: [push, pull_request]

jobs:
  binary:
    name: ${{ matrix.os }} ${{ matrix.cc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cc: gcc
            cxx: g++
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build/
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install cmake doxygen graphviz

      - name: Lint
        uses: cpp-linter/cpp-linter-action@v1.4.4
        with:
          style: file

      - name: Generate project
        run: cmake -B "${{ env.CMAKE_BUILD_DIR }}" -DBUILD_DOCS=1

      - name: Compile
        run: cmake --build "${{ env.CMAKE_BUILD_DIR }}"

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [binary]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build package
        run: |
          cp build/client client
          cp build/server server
          cp -R tools/ .
          cp -R docs/html/ docs/
          zip -r qengine-${{ github.ref_name }}.zip assets/ tools/ docs/ client server

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: qengine-${{ github.ref_name }}.zip
