name: Nightly Build
on:
  workflow_dispatch: ~
  schedule:
    - cron: '0 0 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build/
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install cmake doxygen graphviz

      - name: Generate project
        run: cmake -B "${{ env.CMAKE_BUILD_DIR }}" -DBUILD_DOCS=1

      - name: Compile
        run: cmake --build "${{ env.CMAKE_BUILD_DIR }}"

      - name: Build package
        run: |
          cp build/client client
          cp build/server server
          cp -R tools/ .
          cp -R docs/html/ docs/
          zip -r qengine-nightly.zip assets/ tools/ docs/ client server

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: nightly
          tag_name: nightly
          prerelease: true
          body: Nightly release generated from `master` at 12 AM UTC.
          files: qengine-nightly.zip
